fix(colorpickers): allow no selection on color swatch dialog
zendeskgarden/react-components pull request #1221
Opened 2021-10-04 21:06 UTC by hzhu

🚧 Not ready for review 🚧 

## Description

It was discovered that the color swatch dialog needed to support no color selection. This PR updates the color swatch dialog to support no color selection by accepting `-1` indices.

## Detail

Previously, passing `-1` indices would cause the component to throw an error, since doing a matrix look up (`matrix[-1][-1]`) is invalid. Now, the color swatch dialog handles `-1` indices to mean no selected color. The component now sets `undefined` as a selected color when it encounters `-1` indices. 

I've also updated the controlled and custom icon stories for color swatch dialog to showcase no color selection. There may need to be design follow-ups for this. At this time, color swatch dialog preview defaults to `#fff` when no color is selected. For the custom icon example, it's up to the consumer. In the story, the icon color is defaulted to `#000` to indicate no selection. But this can be something else per design. For e (stroke palette icon to indicate no color selected).

## Checklist

- [ ] :ok_hand: design updates are Garden Designer approved (add the
      designer as a reviewer)
- [x] :globe_with_meridians: demo is up-to-date (`yarn start`)
- [x] :arrow_left: renders as expected with reversed (RTL) direction
- [ ] :metal: renders as expected with Bedrock CSS (`?bedrock`)
- [ ] :wheelchair: analyzed via [axe](https://www.deque.com/axe/) and evaluated using VoiceOver
- [ ] :guardsman: includes new unit tests
- [ ] :memo: tested in Chrome, Firefox, Safari, Edge, and IE11

2021-10-05 06:55 UTC, hzhu commented on packages/colorpickers/src/elements/ColorSwatchDialog/index.tsx
> +    ) {
Alternatively could be `if (controlledSelect && selectedRowIndex > -1 && selectedColIndex > -1)` but unsure why TypeScript isn't liking that.

2021-10-05 13:18 UTC, jzempel requested changes
Something about this doesn't feel great. I think it is fine for the underlying API to know how to operate against `-1` values in conjunction with the container hook. However, as an API consumer I would expect to be able to reset indices via `null` or `undefined`.

2021-10-05 17:12 UTC, hzhu commented
Resetting the indices via `null` or `undefined` changes the component usage from controlled to uncontrolled because those values [indicate](https://github.com/facebook/react/blob/main/packages/react-dom/src/client/ReactDOMInput.js#L39-L42) [uncontrolled](https://github.com/reach/reach-ui/blob/develop/packages/utils/src/dev-utils.ts#L116) [usage](https://github.com/zendeskgarden/react-containers/blob/main/packages/grid/src/useGrid.ts#L81-L87
). The primary reason for not switching between the two is that each type of usage has its own unrelated data management, so mixing the two can be confusing for both API authors and consumers. Some libraries like [React](https://github.com/facebook/react/blob/main/packages/react-dom/src/client/ReactDOMInput.js#L160) and [reach-ui](https://github.com/reach/reach-ui/blob/develop/packages/utils/src/dev-utils.ts#L118) provide warnings to encourage developers to stick to either controlled or uncontrolled, and to not switch between the two. These ideas can be [confusing](https://github.com/facebook/react/issues/17069), so maybe documentation around it or a developer console warning could be added to provide guidance.

2021-10-05 19:29 UTC, jzempel commented
@hzhu thanks for the reminder.

In this case, the prop JSDoc should probably be enhanced a bit. Taking guidance from https://garden.zendesk.com/components/tooltip-modal#tooltipmodal `onClose` maybe something like this?

```tsx
/**
 * Sets the selected row index in a controlled color swatch.
 * Can be set to `-1` to clear the row selection.
 */
selectedRowIndex?: number;
```

2021-10-05 20:12 UTC, hzhu commented on packages/colorpickers/src/elements/ColorSwatchDialog/index.tsx
> +    let controlledSelectedColorColor;
🤣 I'm not suresure. Fix for this variable name incoming, thanks!

2021-10-05 20:15 UTC, hzhu commented on packages/colorpickers/src/elements/ColorSwatchDialog/index.tsx
> +    let controlledSelectedColorColor;
Great question! That's correct, a component must remain a controlled or uncontrolled component throughout its lifecycle. However, component library authors need to build components that support both usages — that's why there are variables associated with both controlled & uncontrolled props.

2021-10-05 20:47 UTC, hzhu commented
@jzempel, the prop descriptions have been updated. Thanks for the great suggestion.

2021-10-05 20:52 UTC, jzempel approved these changes

2021-10-05 21:27 UTC, mtomcal approved these changes
LGTM. Very interesting API decisions on this complicated API. Its very strange to introduce another "unvalue" state, `-1` in this case but completely makes sense given the strong conventions for `undefined` and `null` as indicating "controlled" or "uncontrolled". #onlyinjavascript

2021-10-06 16:01 UTC, slotterbackW approved these changes

2021-10-07 19:17 UTC, Francois-Esquire approved these changes

2021-10-11 15:51 UTC, merged