feat(progress): add useText helper with default value for ARIA label
zendeskgarden/react-components pull request #1443
Opened 2022-10-12 20:31 UTC by jgorfine-zendesk

## Description

Following the convention set forth in the Status Indicator component, this PR adds the `useText` helper to the Progress component. This will both provide a default text label for the component and warn devs if a custom text label hasn't been provided.

This PR relates to [`website` PR #429](https://github.com/zendeskgarden/website/pull/429). 

## Detail

![Screenshot of Progress element with "Progress" ARIA label, verified in Chrome Accessibility tools](https://user-images.githubusercontent.com/93289772/195441839-dc1012a2-a980-4e70-be82-dca0ee2c1c5b.png)

## Checklist

- [x] :ok_hand: design updates will be Garden Designer approved (add the designer as a reviewer)
- [ ] :globe_with_meridians: demo is up-to-date (`yarn start`)
- [x] :arrow_left: renders as expected with reversed (RTL) direction
- [x] :metal: renders as expected with Bedrock CSS (`?bedrock`)
- [x] :guardsman: includes new unit tests. Maintain [existing coverage](https://coveralls.io/github/zendeskgarden/react-components?branch=main) (always >= 96%)
- [x] :wheelchair: tested for [WCAG 2.1 AA](https://www.w3.org/WAI/WCAG21/quickref/?currentsidebar=%23col_customize&levels=aaa) accessibility compliance
- [ ] :memo: tested in Chrome, Firefox, Safari, and Edge

2022-10-13 21:49 UTC, jzempel requested changes
Please add an `aria-label` control to the demo, set to "Label", just like we see with https://zendeskgarden.github.io/react-components/?path=/story/packages-avatars-statusindicator--status-indicator. This allows us to observe component behavior in the demo.

The `args` update can be seen [here](https://github.com/zendeskgarden/react-components/blob/main/packages/avatars/demo/statusindicator.stories.mdx).

2022-10-17 16:27 UTC, jgorfine-zendesk commented
Hey @jzempel, I could use a sanity check. Just added the `'aria-label': 'Label'` line to the Progress component story; and, yet, it appears the custom label isn't making its way into the component:

![Screenshot of Chrome DevTools warning us the Progress component doesn't have a custom label](https://user-images.githubusercontent.com/93289772/196231548-bc8df76f-40e0-4a27-97e5-972412a4b044.png)

At least we know `useText` is working as intended? 😅 

I feel like I'm missing something obvious here, but I'm not sure what.

2022-10-17 18:01 UTC, jzempel commented
@jgorfine-zendesk `args={{ value: 0 }}` is already declared 2 lines above. Add to that declaration like so:

```
args={{ value: 0, 'aria-label': 'Label' }}
```

2022-10-17 18:32 UTC, jgorfine-zendesk commented
Oh! Duh. 

> I feel like I'm missing something obvious here, but I'm not sure what.

Yup, that would be it. 😆 Thanks, @jzempel.

2022-10-17 21:27 UTC, jzempel approved these changes

2022-10-17 21:27 UTC, merged