chore(build): support node 18
zendeskgarden/react-components pull request #1468
Opened 2022-12-05 20:31 UTC by Francois-Esquire

## Description

This PR adds support for node v18 LTS without additional flags.

## Checklist

- [ ] :ok_hand: ~design updates will be Garden Designer approved (add the designer as a reviewer)~
- [ ] :globe_with_meridians: ~demo is up-to-date (`yarn start`)~
- [ ] :arrow_left: ~renders as expected with reversed (RTL) direction~
- [ ] :metal: ~renders as expected with Bedrock CSS (`?bedrock`)~
- [ ] :guardsman: ~includes new unit tests. Maintain [existing coverage](https://coveralls.io/github/zendeskgarden/react-components?branch=main) (always >= 96%)~
- [ ] :wheelchair: ~tested for [WCAG 2.1 AA](https://www.w3.org/WAI/WCAG21/quickref/?currentsidebar=%23col_customize&levels=aaa) accessibility compliance~
- [ ] :memo: ~tested in Chrome, Firefox, Safari, and Edge~

2022-12-06 17:55 UTC, geotrev commented
Interesting. Thought we might need to update some rollup plugins - not needed I guess? :D

2022-12-07 19:15 UTC, jzempel requested changes

2022-12-12 17:01 UTC, Francois-Esquire commented on package.json
> +    "rollup-plugin-size-snapshot": "npm:@brodybits/rollup-plugin-size-snapshot@latest",
@geotrev no particular reason here! @jzempel agreed, will update.

2022-12-12 18:26 UTC, jzempel approved these changes

2022-12-13 15:40 UTC, merged