fix: improves accessibility of Tag close button
zendeskgarden/react-components pull request #1511
Opened 2023-02-06 20:51 UTC by geotrev

## Description

This fix follows the same pattern as the [recent changes](https://github.com/zendeskgarden/react-components/pull/1509) to `File.Close`:

1. Uses a native `button` with `tabindex='-1'` (to prevent tab focus).
2. Wraps `aria-label` with `useText` of `Tag.Close`.
  a. Uses generic text by default (`'Delete'`).

The main thing this fixes, like in `File.Close`, is the operability of `Tag`. When a customer navigates to the component, they'll be able to interact with it in and out of Browse(JAWS/NVDA) and Quick Nav (VO) modes.

Also applies a few reset styles to the icon button.

## Detail

Instead of rendering a `div`, a `button` is provided:

<img width="404" alt="Screen Shot 2023-02-06 at 2 43 02 PM" src="https://user-images.githubusercontent.com/3946669/217080761-edc8158e-3a69-4da1-93f0-83b4168686bd.png">

And the friendly `useText` message is provided when an `aria-label` isn't defined on `Tag.Close`:

<img width="788" alt="Screen Shot 2023-02-06 at 2 47 08 PM" src="https://user-images.githubusercontent.com/3946669/217081511-2175910f-b0bf-413f-8d9c-316507dd45d6.png">

## Checklist

- [x] :ok_hand: design updates will be Garden Designer approved (add the designer as a reviewer)
- [x] :globe_with_meridians: demo is up-to-date (`yarn start`)
- [x] :arrow_left: renders as expected with reversed (RTL) direction
- [x] :metal: renders as expected with Bedrock CSS (`?bedrock`)
- [x] :guardsman: includes new unit tests. Maintain [existing coverage](https://coveralls.io/github/zendeskgarden/react-components?branch=main) (always >= 96%)
- [x] :wheelchair: tested for [WCAG 2.1 AA](https://www.w3.org/WAI/WCAG21/quickref/?currentsidebar=%23col_customize&levels=aaa) accessibility compliance
- [x] :memo: tested in Chrome, Firefox, Safari, and Edge

2023-02-06 22:11 UTC, jzempel requested changes

2023-02-06 22:11 UTC, jzempel commented on packages/tags/src/elements/Close.tsx
> +    const ariaLabel = useText(CloseComponent, props, 'aria-label', 'Delete');
```suggestion
    const ariaLabel = useText(CloseComponent, props, 'aria-label', 'Close');
```

...to align with https://garden.zendesk.com/components/tags#close

2023-02-07 13:56 UTC, jzempel approved these changes

2023-02-07 15:45 UTC, Francois-Esquire approved these changes

2023-02-08 16:18 UTC, merged