feat!: rename DrawerModal to Drawer
zendeskgarden/react-components pull request #1715
Opened 2024-02-21 19:18 UTC by geotrev

## Description

Renames `DrawerModal` to `Drawer` to match [website language](https://garden.zendesk.com/components/drawer).

## Detail

No discrete component code was changed.

## Checklist

- ~~:ok_hand: design updates will be Garden Designer approved (add the designer as a reviewer)~~
- ~~:globe_with_meridians: demo is up-to-date (`npm start`)~~
- ~~:arrow_left: renders as expected with reversed (RTL) direction~~
- ~~:metal: renders as expected with Bedrock CSS (`?bedrock`)~~
- ~~:guardsman: includes new unit tests. Maintain existing coverage (always >= 96%)~~
- ~~:wheelchair: tested for WCAG 2.1 AA accessibility compliance~~
- ~~:memo: tested in Chrome, Firefox, Safari, and Edge~~

2024-02-21 19:32 UTC, geotrev commented on packages/modals/README.md
> +```
Seemed worth including these. .

2024-02-22 14:56 UTC, jzempel requested changes
Please add `migration.md` details

2024-02-22 19:15 UTC, jzempel approved these changes
Approved, with a potential [nit] modification. Feel free to merge when ready.

2024-02-22 19:15 UTC, jzempel commented on docs/migration.md
> +- `DrawerModal`: renamed to `Drawer`
[nit] can we alphabetize component bullet lists under the package headings?

2024-02-22 20:37 UTC, jzempel approved these changes

2024-02-22 20:44 UTC, merged