🚧 feat(draggable): recolors components with new palette
zendeskgarden/react-components pull request #1805
Opened 2024-05-09 16:38 UTC by geotrev

## Description

Colors updated for the following components & stories using new v9 color palette:

Components:
- Draggable
    - Draggable.Grip
- DraggableList.DropIndicator
- Dropzone

## Detail

Here is a full breakdown of colors changed: 

### Draggable

| State        | V8 Color (old) | V9 Color (new) |
| --------- | -------------- | --------------- |
| Default – Border | `neutral-300` | `border.default` |
| Default – Foreground | `foreground` | `foreground.default` |
| Default – Background | `transparent` | `transparent` |
| Hover – Background | `primary-600` / `0.08` | `background.primaryEmphasis` (offsets: dark `-100`) |
| `isGrabbed` – Shadow | `neutral-600` / `0.35` (lg) | `neutral-1200` (lg) (transparency: light `200`, dark `1000` |
| `isGrabbed` – Background | `background` | `background.raised` |
| Disabled – Border | `transparent` | `transparent` |
| Disabled – Foreground | `neutral-400` | `foreground.subtle` (offsets: light `-100`, dark `200`|
| Disabled – Background | `neutral-200` | `background.emphasis` (offsets: dark `-100`) |
| Placeholder - Background | `neutral-800` / `0.1` | `background.emphasis` (offsets: dark `-100`) |

### Draggable.Grip

### DraggableList.DropIndicator

### Dropzone

## Checklist

- [ ] :ok_hand: design updates will be Garden Designer approved (add the designer as a reviewer)
- [ ] :globe_with_meridians: demo is up-to-date (`npm start`)
- [ ] :arrow_left: renders as expected with reversed (RTL) direction
- [ ] :metal: renders as expected with Bedrock CSS (`?bedrock`)
- [ ] :guardsman: includes new unit tests. Maintain existing coverage (always >= 96%)
- [ ] :wheelchair: tested for WCAG 2.1 AA accessibility compliance
- [ ] :memo: tested in Chrome, Firefox, Safari, and Edge

2024-05-13 16:54 UTC, geotrev commented
Waiting for new disabled color variables from #1806

2024-05-14 15:03 UTC, jzempel requested changes

2024-05-14 15:03 UTC, jzempel commented on packages/drag-drop/src/styled/dropzone/StyledDropzone.ts
> +      transparency: theme.opacity[100],
Can remove `transparency` – already built-in

2024-05-14 20:48 UTC, geotrev commented on packages/drag-drop/src/styled/draggable-list/StyledDropIndicator.ts
> +  const color = getColor({ variable: 'foreground.primary', theme });
That's fair. I was teetering between fg and border, anyway. :)

2024-05-14 20:58 UTC, geotrev commented on packages/drag-drop/demo/~patterns/stories/components.tsx
> +  color: ${p => getColor({ variable: 'foreground.default', theme: p.theme })};
I also just realized I can convert this to a more semantically correct `h2`.

2024-05-15 13:29 UTC, jzempel commented on packages/drag-drop/demo/~patterns/stories/components.tsx
> +  color: ${p => getColor({ variable: 'foreground.default', theme: p.theme })};
[nit] the `h2` still has the bold font weight problem. Would it be better to use Garden's `<LG tag="h2">` typography component? We just don't want to confuse any consumers that view the pattern.

2024-05-16 13:22 UTC, geotrev commented on packages/drag-drop/demo/~patterns/stories/components.tsx
> +  color: ${p => getColor({ variable: 'foreground.default', theme: p.theme })};
Yeah that makes sense. I'll update.

2024-05-16 15:31 UTC, jzempel approved these changes

2024-05-16 19:02 UTC, merged