docs: add removal of `theme` default prop ADR
zendeskgarden/react-components pull request #1914
Opened 2024-09-06 21:14 UTC by ze-flo

## Description

Adds the "Removal of `theme` default prop" ADR. See reference PR for context: https://github.com/zendeskgarden/react-components/pull/1905

2024-09-09 16:45 UTC, geotrev requested changes
Looking good!

2024-09-09 16:45 UTC, geotrev commented on docs/adrs/README.md
> +- [ADR-002](./002-theme-default-prop-removal.md): Remove of `theme` default prop
```suggestion
- [ADR-002](./002-theme-default-prop-removal.md): Removal of `theme` default prop
```

2024-09-09 16:46 UTC, geotrev commented on docs/adrs/README.md
> +- [ADR-002](./002-theme-default-prop-removal.md): Remove of `theme` default prop
Alternatively: "Require `ThemeProvider` in all cases"

2024-09-09 18:06 UTC, jzempel approved these changes

2024-09-10 17:45 UTC, geotrev approved these changes

2024-09-10 17:46 UTC, merged