chore(packageName): update prop descriptions
zendeskgarden/react-components pull request #959
Opened 2020-12-21 18:17 UTC by Mikaelia

## Description

Updates grid package prop docs

2020-12-21 22:09 UTC, jzempel requested changes
For all use of `col`, I think it would be better to replace with `column`. We would say `Col` only if there was a particular reference to the component itself.

2020-12-21 22:09 UTC, jzempel commented on packages/grid/src/elements/Col.tsx
> +   *  See [breakpoints](https://garden.zendesk.com/components/theme-object#default_theme).
Let's use the `website`-local URL here, and maybe change to `/components/theme-object#breakpoints`

2020-12-21 22:09 UTC, jzempel commented on packages/grid/src/elements/Row.tsx
> +   * This affects vertical `Col` alignment on all screen sizes.
Yes, agreed on this use of `Col` 👍

2020-12-22 16:57 UTC, jzempel reviewed
Any thoughts on https://github.com/zendeskgarden/react-components/pull/959#pullrequestreview-556692567?

2020-12-22 17:40 UTC, Mikaelia commented
Ah yes, just updated!

2020-12-22 17:43 UTC, jzempel approved these changes

2020-12-23 20:05 UTC, merged