chore(tabs): update prop descriptions
zendeskgarden/react-components pull request #964
Opened 2020-12-21 20:47 UTC by Mikaelia

## Description
Updates tabs package prop descriptions

2020-12-21 22:55 UTC, jzempel requested changes

2020-12-21 22:55 UTC, jzempel commented on packages/tabs/src/elements/Tab.tsx
> +  /** Defines a unique value to identify the tab. Provided to the `onChange` event in the tabs component. */
In this case, an explicit component reference might be best as:

```
[Tabs](#tabs)
```

2020-12-21 22:55 UTC, jzempel commented on packages/tabs/src/elements/Tabs.tsx
> +   * @param {String} selectedItem The selected tab's `item` value
Suggest replacing ~selectedItem~ with `updatedSelectedItem`. Or, alternatively, updating the TS signature if that is preferable.

2020-12-22 17:15 UTC, hzhu approved these changes

2020-12-22 17:17 UTC, jzempel approved these changes

2020-12-23 20:07 UTC, merged